services:
  # Banco de Dados PostgreSQL
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql
    networks:
      - app_network

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_web
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app_network

  # Flask API
  flask_api:
    build:
      context: ./flask_api
    container_name: flask_api
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: "postgresql://admin:supersecret@db:5432/app_db?options=-csearch_path=flask_schema"
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_DEBUG: 1
    depends_on:
      - db
    volumes:
      - ./flask_api:/app
    networks:
      - app_network

  # Flask API 2
  flask_api2:
    build:
      context: ./flask_api
    container_name: flask_api2
    ports:
      - "5003:5000"
    environment:
      DATABASE_URL: "postgresql://admin:supersecret@db:5432/app_db?options=-csearch_path=flask_schema"
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_DEBUG: 1
    depends_on:
      - db
    volumes:
      - ./flask_api:/app
    networks:
      - app_network

  # Laravel API
  laravel_api:
    build:
      context: ./laravel_api
      dockerfile: Dockerfile
    container_name: laravel_api
    restart: always
    ports:
      - "5002:8000"
    volumes:
      - ./laravel_api:/var/www/html
    environment:
      APP_ENV: local
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: app_db
      DB_USERNAME: admin
      DB_PASSWORD: supersecret
      DB_SCHEMA: laravel_schema
    depends_on:
      - db
    networks:
      - app_network

  # Laravel API 2
  laravel_api2:
    build:
      context: ./laravel_api
      dockerfile: Dockerfile
    container_name: laravel_api2
    restart: always
    ports:
      - "5004:8000"
    volumes:
      - ./laravel_api:/var/www/html
    environment:
      APP_ENV: local
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: app_db
      DB_USERNAME: admin
      DB_PASSWORD: supersecret
      DB_SCHEMA: laravel_schema
    depends_on:
      - db
    networks:
      - app_network

  # Gateway (NGINX)
  gateway:
    build: ./gateway
    container_name: api_gateway
    ports:
      - "8080:80"
    depends_on:
      - flask_api
      - flask_api2
      - laravel_api
      - laravel_api2
    networks:
      - app_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app_network:
    driver: bridge